# Generated by Django 5.0.3 on 2024-04-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transcations", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Transcation",
            new_name="Balance",
        ),
    ]
