# Generated by Django 5.0.3 on 2024-04-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcations", "0002_rename_transcation_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="category",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Investment", "Investment"),
                    ("Medical", "Medical"),
                    ("Miscellaneous", "Miscellaneous"),
                ],
                default="Miscellaneous",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="balance",
            table="transactions",
        ),
    ]
