# Generated by Django 5.0.3 on 2024-04-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcations", "0003_balance_category_alter_balance_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="tag",
            field=models.CharField(
                choices=[("Income", "Income"), ("Expense", "Expense")],
                default="Expense",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
