# Generated by Django 5.0.3 on 2024-04-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transcations", "0004_balance_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balance",
            name="balance",
        ),
    ]
