# Generated by Django 5.0.3 on 2024-04-10 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transcations",
            "0006_rename_transcation_date_balance_transaction_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customer",
            table="customer",
        ),
        migrations.CreateModel(
            name="Statements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monthly_statement", models.FileField(null=True, upload_to="")),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transcations.customer",
                    ),
                ),
            ],
            options={
                "db_table": "statements",
            },
        ),
    ]
