# Generated by Django 5.0.4 on 2024-04-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0007_alter_customer_table_statements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statements',
            name='monthly_statement',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
